version: "3.2"

services:

    db:
      image: mysql:5.7
      restart: "${RESTART_POLICIES}"
      volumes:
        - "./.data/db:/var/lib/mysql"
      environment:
        - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        - "MYSQL_DATABASE=${MYSQL_DATABASE}"
        - "MYSQL_USER=${MYSQL_USER}"
        - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      networks:
        - "wordpress"

    wordpress:
      image: wordpress:latest
      restart: "${RESTART_POLICIES}"
      ports:
        - "${WORDPRESS_PORT}:80"
      volumes:
        - "./.data/html:/var/www/html"
      environment:
        - "WORDPRESS_DB_HOST=db:3306"
        - "WORDPRESS_DB_USER=${MYSQL_USER}"
        - "WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}"
        - "WORDPRESS_DB_NAME=${MYSQL_DATABASE}"
      networks:
        - "wordpress"


networks:

    wordpress:
        driver: bridge
