  version: '2'

  services:
    db:
      image: mysql:5.7
      container_name: db
      restart: "${RESTART_POLICIES}"
      volumes:
        - "./.data/db:/var/lib/mysql"
      environment:
        - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        - "MYSQL_DATABASE=${MYSQL_DATABASE}"
        - "MYSQL_USER=${MYSQL_USER}"
        - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: "${RESTART_POLICIES}"
      depends_on:
        - "db"
      links:
        - "db"
      ports:
        - "${PMA_PORT}:80"
      environment:
        - "PMA_HOST=db"
        - "PMA_USER=${MYSQL_USER}"
        - "PMA_PASSWORD=${MYSQL_PASSWORD}"

    wordpress:
      image: wordpress:latest
      container_name: wordpress
      restart: "${RESTART_POLICIES}"
      depends_on:
        - "db"
      links:
        - "db"
      ports:
        - "${WORDPRESS_PORT}:80"
      volumes:
        - "./.data/html:/var/www/html"
      environment:
        - "WORDPRESS_DB_HOST=db:3306"
        - "WORDPRESS_DB_USER=${MYSQL_USER}"
        - "WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}"
        - "WORDPRESS_DB_NAME=${MYSQL_DATABASE}"
